heat_template_version: 2014-10-16

parameters:
  agent_image:
    type: string
    default: heat-docker-atomic-agents
  docker_registry:
    type: string
    default: 10.18.57.202:8080

resources:
  install_docker_agents:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          params:
            $agent_image: {get_param: agent_image}
            $docker_registry: {get_param: docker_registry}
          template: {get_file: ./fragments/start_docker_agents.sh}
outputs:
  config:
    value: {get_resource: install_docker_agents}
