FROM kollaglue/centos-rdo-nova-libvirt
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name libvirt --privileged --net=host --restart=always --env-file=/etc/nova-compute.env kollaglue/centos-rdo-nova-libvirt:latest"
