FROM kollaglue/centos-rdo-glance-api
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name glance-api --net=host --restart=always --env-file=/etc/openstack.env kollaglue/centos-rdo-glance-api:latest"
