FROM kollaglue/centos-rdo-nova-network
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name nova-network --net=host --restart=always --privileged --env-file=/etc/nova-compute.env kollaglue/centos-rdo-nova-network"
