FROM rthallisey/fedora-rdo-glance-registry
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name glance-registry --net=host --restart=always --env-file=/etc/openstack.env rthallisey/fedora-rdo-glance-registry:latest"

