FROM kollaglue/centos-rdo-rabbitmq
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name rabbitmq --net=host --restart=always --env-file=/etc/rabbitmq.env kollaglue/centos-rdo-rabbitmq"
