FROM imain/fedora-rdo-keystone
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name keystone --net=host --restart=always --env-file=/etc/openstack.env imain/fedora-rdo-keystone"
