FROM imain/fedora-rdo-mariadb
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name mariadb --net=host -v /var/lib/mysql:/var/lib/mysql -v /var/log/mariadb:/var/log/mariadb --env-file=openstack.env imain/fedora-rdo-mariadb"
