FROM imain/fedora-rdo-nova-api
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name nova-api --privileged --net=host --restart=always --env-file=/etc/openstack.env imain/fedora-rdo-nova-api:latest"
