FROM kollaglue/centos-rdo-mariadb
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name mariadb --net=host --env-file=/etc/openstack.env -v /var/lib/mysql:/var/lib/mysql -v /var/log/mariadb:/var/log/mariadb kollaglue/centos-rdo-mariadb"
