FROM imain/fedora-rdo-nova-compute
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --privileged \
       -v /sys/fs/cgroup:/sys/fs/cgroup \
       -v /var/lib/nova:/var/lib/nova \
       -v /run:/run \
       -v /etc/libvirt/qemu:/etc/libvirt/qemu \
       --pid=host --net=host \
       --env-file=/etc/openstack.env imain/fedora-rdo-nova-compute"
