FROM kollaglue/centos-rdo-nova-libvirt
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name libvirt --privileged --net=host --restart=always --env-file=/etc/openstack.env IMAGE"
