FROM kollaglue/centos-rdo-nova-conductor
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name nova-conductor --net=host --restart=always --env-file=/etc/nova-controller.env kollaglue/centos-rdo-nova-conductor"
