FROM kollaglue/centos-rdo-keystone
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name keystone --net=host --restart=always --env-file=/etc/keystone.env kollaglue/centos-rdo-keystone"
