FROM imain/fedora-rdo-nova-scheduler
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run --name nova-scheduler -d --net=host \
               --env-file=/etc/openstack.env imain/fedora-rdo-nova-scheduler"
