FROM imain/fedora-rdo-nova-scheduler
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name nova-scheduler --net=host --restart=always --env-file=/etc/openstack.env imain/fedora-rdo-nova-scheduler"
