FROM kollaglue/centos-rdo-glance-registry
MAINTAINER Ryan Hallisey <rhallise@redhat.com>

LABEL INSTALL="docker run -d --name glance-registry --net=host --restart=always --env-file=/etc/glance.env kollaglue/centos-rdo-glance-registry:latest"

